### ISSUE TITLE
Checks for section ID can break functionality if section file is named incorrectly

### ISSUE THREAD

**Issue by ConduciveMammal** [mirceapiturca/Sections#16]
Being in the UK, I naturally named this section `app-optimisation.liquid`, however, the scripts in the file are checking for exactly `app-optimization`. If these don't match up, the whole section fails to render. I'd suggest an alternative method of getting the Section ID.

Fails from:
`if (evt.detail.sectionId !== 'app-optimisation') return;`

**Comment by mirceapiturca** [comment]
Hey Liam
Yes, I see the issue here.
I think that something like this should do the trick:
`if (evt.detail.sectionId !== {{ section.id }}) return;`

I need to test it and will update the code.

Thanks

**Comment by ae-1972** [comment]
@mirceapiturca 

Did you test it and update the code ?

**Comment by ae-1972** [comment]
> Being in the UK, I naturally named this section `app-optimisation.liquid`, however, the scripts in the file are checking for exactly `app-optimization`. If these don't match up, the whole section fails to render. I'd suggest an alternative method of getting the Section ID.
> 
> Fails from: `if (evt.detail.sectionId !== 'app-optimisation') return;`

@ConduciveMammal did you test the code ?

**Comment by ConduciveMammal** [comment]
Apologies for the late response.

`if (evt.detail.sectionId !== {{ section.id }}) return;`

This did indeed fix the issue for me.
