### ISSUE TITLE
ACCORDION ANIMATION IS NOT WORKING

### ISSUE THREAD

**Issue by Obykanoby** [mirceapiturca/Sections#18]
Hello, first of all thank you very much for providing this valuable asset to the public. I followed the steps and successfully added the FAQ to my theme and everything works perfectly but Ive added a title and content to my FAQ when I click on the title, the answer doesn't unfold, it remains still. Do you know what could possibly cause thank? Again, thank you very much

**Comment by mirceapiturca** [comment]
Hi,
Can you please send me a link to the FAQ?
Thanks

**Comment by Obykanoby** [comment]
Hello, sure
https://midnightarchive.myshopify.com/pages/faq
I also made a small video indicating the issue.
https://www.loom.com/share/4c30a6167a094b83bb7f6e8730b34946

**Comment by mirceapiturca** [comment]
Is this file uploaded to your assets folder? https://github.com/mirceapiturca/Sections/blob/master/FAQ/assets/faq.js

**Comment by Obykanoby** [comment]
Yes, take a look at the screenshot

**Comment by mirceapiturca** [comment]
<img width="687" alt="Screenshot 2023-02-28 at 11 57 22" src="https://user-images.githubusercontent.com/861214/221819235-4cffff84-9a67-428c-ac0d-4d8aefb838ec.png">

faq.js doesn't appear to be added to the assets folder. I was unable to see this JS file from your video. Please see my screenshot, there is a 404 error for that file.

**Comment by Obykanoby** [comment]
Yea, I dont know whats going on, im confused. As you can see in this video,
I have uploaded both assets and section files but I noticed that when I am
searching FAQ, they don't appear. I don't know what might be the issue. I
tried to redo the process but the same thing happens.
https://www.loom.com/share/e7be72d4e52b404baaff00458ca30860

**Comment by mirceapiturca** [comment]
No worries,
I've sent a collaborator request to your store.
Once granted I will be able to have a look at the issue.

**Comment by mirceapiturca** [comment]
Filenames are case-sensitive. You named it `FAQ.js`, it should if been `faq.js`.
I've renamed it and it is all good now.

**Comment by Obykanoby** [comment]
Well, that was silly. Thank you very much for your time! Wish you all the
best
