### ISSUE TITLE
Development stores - apps injection

### ISSUE THREAD

**Issue by yoyurec** [mirceapiturca/Sections#21]
Somehow in **Development stores** (https://shopify.dev/docs/themes/tools/development-stores) apps throws their scripts not to sHopify object, but to HTML in a "classic way" via `<script src="..."` 🤔

For example Accessibily - https://apps.shopify.com/accessibly-app
![image](https://github.com/mirceapiturca/Sections/assets/137919/5eed4d02-14cf-40cd-b327-61a34f9485fe)

Issues:
* no apps detected in section
![image](https://github.com/mirceapiturca/Sections/assets/137919/41623a04-aa1e-4ef3-8fbe-e596694b253f)
* as result - optimization don't work, even "tuned" version - https://github.com/mirceapiturca/Sections/pull/13

How to block/postpone loading apps in this case?
Is it possible to update your optimizator somehow?

**Comment by mirceapiturca** [comment]
No,
The section will only "catch" scripts injected via the ScriptTag API.

I am not sure how that app is adding the script. I assume they modify the template via the Asset API. You could probably use {% capture %} and create your own load logic in that case.
